### ISSUE TITLE
Build fails on Windows, help needed

### ISSUE THREAD

**Issue by Nolram12345** [project-imprimis/libprimis#167]
**Describe the issue**
Imprimis fails building on Windows 10, 64bit.

**Expected behavior**
Imprimis building without error.

**Important Information:**
Error :
https://hastebin.com/ocapiluhop.sql

**Comment by no-lex** [comment]
As best as I can tell, it appears you are missing the libsdl2 library needed to compile the game. It should be possible to get the development version (the standard library will *not* be sufficient to compile the game) from the SDL2 (Simple DirectMedia Layer) website.

Currently the project is very small, and lacks any Windows systems with which to verify builds against, so at this early stage in development Windows builds may not be always in perfectly working order. If you have further issues building, I'm happy to help sort things out as best as I can.

I should add that you will need to also compile the game server and run that as well in order to play the game. This is somewhat clumsy right now, but hopefully is understandable given that Imprimis is still firmly in the pre-alpha stage.

**Comment by Nolram12345** [comment]
Huh, okay. This is very unfortunate, guess I will have to play around to get it to work.

**Comment by no-lex** [comment]
https://github.com/project-imprimis/libprimis/commit/6bffed3b81ae84f99f07a4c470e132bf7106ecb9 also added some instructions for Windows building of the library. Hopefully this helps.

There is also an alpha of the game that comes already compiled as a pre-release alpha in the `imprimis` repository releases section. Note that a server is also needed to play the game (though there is a public server hosted at `67.171.21.10`).
