### ISSUE TITLE
Graphics settings sliders behave unexpectedly

### ISSUE THREAD

**Issue by nonoesimposible** [project-imprimis/libprimis#198]
**Describe the issue**
In the options tab, clicking the arrows of a `UIlistslider` goes through an unpredictable pattern of options and sometimes skips some. For instance, this happens when trying to adjust anisotropic filtering:

https://user-images.githubusercontent.com/39754510/107158233-035d3780-6946-11eb-8fb0-f2da80507254.mp4

This also happens on other sliders, like the "Stains" in the "Graphics" only showing "quick-fade" with the right arrow.

**Expected behavior**
The same options should be shown in a consistent order: clicking the left arrow repeatedly should go through the options in the opposite order that clicking the right arrow would, and neither should skip an option. Additionally, since most of our target users speak left-to-right languages and "read" interfaces from left to right, the options should arguably get more demanding when pressing the right arrow.

**Important Information:**
OS: Arch Linux
Reproduced on 0.2a "Ballard" (bed40e0) and 0.1 "Aix" (14c2808), so the issue has been around for a long time. I will try to find the exact commit which introduced the issue later.

**Comment by no-lex** [comment]
Most likely caused by 2fd25c154348974379f3abbbd0cedb2816b60317.

**Comment by coornio** [comment]
Can confirm that this is no issue on the cubescript side as the code is identical with the working version. Culprit is most likely the changes @no-lex mentioned, more particularly any code related to the `doargs` function whose purpose is to forward argument values from a parent to a child. Without it, the action block of UIarrowbutton inside of UIlistslider would require all arg calls to be using appropriate amounts of @ instead of the current $, as well as make the code fundamentally slower on a technical level. You may use such a workaround in the meantime to get the current menus working while you attempt to troubleshoot how the std changes broke it.

**Comment by azkoon** [comment]
The menus seem to still be affected as of alpha 7, additionally:
- "Auto Sort" in server list seems to be checking itself on and off when hovering the mouse over various elements,
- "Soft Particles" button simply throws
```
unknown alias lookup: softparticles
  2) UIbutton
  1) UIbutton
```
in the chat log without otherwise reacting in a visible way.

**Comment by azkoon** [comment]
It would appear that changing resolution settings still tends to cause segfaults when scaling is set to better quality.

**Comment by no-lex** [comment]
Caused by https://github.com/project-imprimis/libprimis/commit/6b682497dc02cf5df763341fdac337ab5ce28112 improperly reformatting `LISTFIND`.
